version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sato342705
      POSTGRES_DB: development_db
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:Sato342705@db:5432/development_db