# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  # adapter: sqlite3
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Sato342705
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # database: db/development.sqlite3
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: production_db
