default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: Sato342705
  pool: 5

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: production_db
  host: spotsnap-db.cf4ymowi0716.us-east-1.rds.amazonaws.com
  username: postgres
  password: Sato342705
  port: 5432

  
  
