default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: Sato342705
  pool: 5

development:
  <<: *default
  database: development_db

test:
  <<: *default
  database: test_db

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: production_db
  host: db
  username: postgres
  password: Sato342705
  pool: 5
  
