default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: development_db
  host: localhost
  username: postgres
  password: Sato342705

test:
  <<: *default
  database: test_db

production:
  <<: *default
  database: production_db
  host: 0.0.0.0
  username: postgres
  password: Sato342705
  
